import { expect, test, type Locator } from "@playwright/test";

test("backgrounds, real menu input, fishing, pause and test picker across browser engines", async ({ page, browserName }, info) => {
  const errors: string[] = [];
  page.on("pageerror", e => errors.push(e.message));
  page.on("response", r => { if (r.status() >= 400) errors.push(`${r.status()} ${r.url()}`); });
  const touch = browserName === "webkit";
  const activate = (locator: Locator) => touch ? locator.tap() : locator.click();
  const action = (name: string) => activate(page.locator(`[data-action="${name}"]`));
  await page.goto("./");
  await page.clock.install();
  await expect.poll(() => page.locator("#title-backdrop").evaluate((e: HTMLImageElement) => e.complete && e.naturalWidth > 0)).toBe(true);
  await page.screenshot({ path: `test-results/${info.project.name}-title.png` });
  await action("settings");
  await action("haptic-test");
  await expect(page.locator("#toast")).toBeVisible();
  await action("close-settings");
  await action("play");
  await action("enter-lake");
  await expect(page.locator("#game")).toHaveAttribute("data-state", "READY");
  await action("picker");
  await action("pick-northern-pike");
  await expect(page.locator('[data-action="pick-northern-pike"]')).toHaveAttribute("aria-pressed", "true");
  await page.screenshot({ path: `test-results/${info.project.name}-picker.png` });
  await action("confirm-creature");
  await activate(page.locator("#action"));
  for (let i = 0; i < 62 && await page.locator("#game").getAttribute("data-state") !== "BITE"; i++) await page.clock.runFor(100);
  await expect(page.locator("#game")).toHaveAttribute("data-state", "BITE");
  await activate(page.locator("#action"));
  await expect(page.locator("#game")).toHaveAttribute("data-state", "FIGHT");
  await action("settings");
  await page.clock.runFor(10000);
  await expect(page.locator("#game")).toHaveAttribute("data-state", "FIGHT");
  const modal = (await page.locator(".modal").boundingBox())!;
  expect(modal.y).toBeGreaterThanOrEqual(0);
  expect(modal.y + modal.height).toBeLessThanOrEqual(page.viewportSize()!.height);
  await page.screenshot({ path: `test-results/${info.project.name}-settings.png` });
  await action("close-settings");
  await page.clock.runFor(3400);
  await expect(page.locator("#game")).toHaveAttribute("data-state", "FAILURE");
  await page.clock.runFor(1500);
  await expect(page.locator("#game")).toHaveAttribute("data-state", "READY");
  await action("book");
  await expect(page.locator(".creature-card.discovered")).toHaveCount(0);
  await page.screenshot({ path: `test-results/${info.project.name}-book.png` });
  await action("book-back");
  await expect(page.locator(".lake-intro")).toHaveCount(0);
  expect(errors).toEqual([]);
});
